name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm i -g npm
      - run: npm run setup
      - run: npm run test
